### ISSUE TITLE
只有百科的那个命令有用

### ISSUE THREAD

**Issue by Sasa-kid** [azmiao/destiny2_hoshino_plugin#2]
![QQ图片20201205125814](https://user-images.githubusercontent.com/68634616/101234377-aea90080-36f9-11eb-9685-2e37b4690b4e.png)
其他涉及到发图的命令都报错，这是我的问题吗？

**Comment by azmiao** [comment]
> ![QQ图片20201205125814](https://user-images.githubusercontent.com/68634616/101234377-aea90080-36f9-11eb-9685-2e37b4690b4e.png)
> 其他涉及到发图的命令都报错，这是我的问题吗？

我这边拉去测试了一下还是没问题的，你看看cookie写入了吗，写入一般就没啥问题了，其他问题你复制到百度一下应该能解决

**Comment by azmiao** [comment]
> ![QQ图片20201205125814](https://user-images.githubusercontent.com/68634616/101234377-aea90080-36f9-11eb-9685-2e37b4690b4e.png)
> 其他涉及到发图的命令都报错，这是我的问题吗？

这大概是str和messagesegment类型不兼容的意思？我也不太清楚，我个人感觉是messagesegment这个类的问题，不过Nonebot的aiocqhttp是确实自带这个库的，所以我这暂时没遇到这问题，我后续有空改改发送方式试试吧

**Comment by azmiao** [comment]
> ![QQ图片20201205125814](https://user-images.githubusercontent.com/68634616/101234377-aea90080-36f9-11eb-9685-2e37b4690b4e.png)
> 其他涉及到发图的命令都报错，这是我的问题吗？

你试试在destiny2.py文件里，把周报那一块的msg = msg + img1换成msg = msg + str(img1)试试，如果可以后面老九什么的也自己换一下

**Comment by Sasa-kid** [comment]
改了之后没问题了，感谢

**Comment by azmiao** [comment]
> 改了之后没问题了，感谢

ok,下次我提交代码的时候顺便也改一下
