### ISSUE TITLE
一个小小的描述错误

### ISSUE THREAD

**Issue by Sasa-kid** [azmiao/destiny2_hoshino_plugin#3]
发现星期三的周报更新提示描述为试炼周报，而直接发命令"周报 "的回复的标题是周报
![QQ截图20201224131923](https://user-images.githubusercontent.com/68634616/103063052-1d87c400-45eb-11eb-9338-a2c2e22f9c74.png)

**Comment by azmiao** [comment]
> 发现星期三的周报更新提示描述为试炼周报，而直接发命令"周报 "的回复的标题是周报
> ![QQ截图20201224131923](https://user-images.githubusercontent.com/68634616/103063052-1d87c400-45eb-11eb-9338-a2c2e22f9c74.png)

哦哦对哦，写错了hhhhhhh，已经改好了

**Comment by azmiao** [comment]
ok
