### ISSUE TITLE
命令可正常使用，但是查询帮助无反应

### ISSUE THREAD

**Issue by Kelcoin** [azmiao/destiny2_hoshino_plugin#4]
![image](https://user-images.githubusercontent.com/10922375/110068505-dbc88600-7db0-11eb-923a-71aa53dce841.png)
![image](https://user-images.githubusercontent.com/10922375/110068572-f438a080-7db0-11eb-8566-a99fe687c100.png)

**Comment by azmiao** [comment]
现已修复，`destiny2.py`里加几句话就行了，当时忘记改了
